### PR TITLE
#9 Get jenkins to work for feature branches

### PR DESCRIPTION
**Pull request by bruderol**
* Sanitized branch names to not fail on branch names like this branch here
* Documented a little bit better how to choose proper branch and build names (more tricky than one might think)
* getting webhook trigger for pushes to github right in jenkins pipeline
* get notifications working for Pull Requests (no change in this PR, had to adjust Jenkins config for it)

### CODE REVIEW

**Comment by bruderol** [comment]
funny that this Pr is green although the build says failed :-(

**Comment by bruderol** [comment]
hmm, builds are still not reported back to github here :-( dont know why

**Comment by bruderol** [comment]
@ideco please review and merge - this will fix build problem with feature branches

**Comment by ideco** [comment]
There seems to be a mix of tabs and spaces in the Jenkinsfile, but we can merge this as is. I'll clean it up in a follow-up (I'm not on my laptop currently)

**Comment by bruderol** [comment]
@ideco the wrong tabs might have been introduced by me - maybe because I edited in github frontend - sorry for that ;-)

**Pull request merged**
