### PR TITLE
#17 migrate example to junit 5

### PR DESCRIPTION
**Pull request by bruderol**
minimal migration to junit 5

for some advanced ideas how to improve it further see #20 

I think it looks nice - was quite easy.

@adiherzog and @ideco what do you think?

### CODE REVIEW

**Comment by bruderol** [comment]
@mi-we becaue you asked me today - here is the first version with junit 5 ... ;-)

**Comment by bruderol** [comment]
hmm, bei mir lokal läuft's - keine Ahnung warum unser jenkins das junit5 plugin im gradle build file nicht mag 👎

**Comment by adiherzog** [comment]
Looks good, I like the new concept with ExtendWith and the various callbacks that can be implemented.

You can merge once the CI is happy.

Regarding JUnit 4 we can just add a note in the README.md and point to the last commit (or tag) before the upgrade, so that people still see how it's done with JUnit 4. That's probably the most lightweight solution.

**Review by adiherzog — APPROVED** [review]

**Comment by bruderol** [comment]
@adiherzog that is more or less what I did - but as a branch - didnt you see it in the readme?

**Comment by bruderol** [comment]
@adiherzog there was still a lot missing - now it should work on the build:
1. had to update gradle wrapper to work with junit 5 plugin
2. junit 5 comes with different assertions, I migrated to those
3. some cleanup of dependencies and imports 
4. updated all junit dependencies to newest versions (5.0.2 & 1.0.2)

@adiherzog or @ideco you could klick on merge once the build is green

**Review by adiherzog — APPROVED** [review]

**Pull request merged**
