### PR TITLE
Feature/15 cleanup scenarioo report data

### PR DESCRIPTION
**Pull request by bruderol**
PR for #15 

* Cleanup scripts to remove pizza example docu data for branches not existing anymore and delete old builds
* Improved Jenkins build to report where the reports can be found
* Improved Jenkins build to also deploy reports in case of test failures

### CODE REVIEW

**Comment by bruderol** [comment]
cleanup sollte so weit zu gehen ---- allerdings scheint das deployment der reports nicht mehr zu funken - ev. REST schnittstelle fürs ZIP deployment auf neuem demo server anders konfiguriert? Paswwort?

funktioniert auch auf dem master branch im pizza beispiel nicht mehr (letztes mal hat es für build 6 auf master geklappt)

@adiherzog @ideco irgend eine Ahnung warum das nicht mehr geht???

**Comment by bruderol** [comment]
@ideco now the cleanup is working - the upload as well - there was a problem because of the changed tomcat user password - I also adjusted the upload curl command to fail the build, if the call returns http error code (-f option).

**Comment by bruderol** [comment]
@ideco would be great if you could review and merge - should be ok now

**Comment by ideco** [comment]
Nice job! Now we won't have so much junk lying around con our demos :-)

**Comment by bruderol** [comment]
@ideco thanks for fast merging! Enjoy the weekend!

@adiherzog 
I will now introduce a develop branch for pizza example as well such that we are consistent on all our repos - why this is useful: we can release new version of the example in case of breaking changes in the writer - following same process as for all our repos. And the master demo will be working with the old version until we release a new version. 
Already prepared is the pipeline: Master pizza example will allways publish to master demo of scenarioo, but develop and all other branches will allways publish to develop demo.

**Pull request merged**
